require("config.keymap")
require("config.options")
require("config.autocmds")
require("config.lsp")
require("config.lazy")
require("config.treesitter")
require("config.plugins")
require("config.builtin_plugins")
